spotify:
  client_id: d93612e1cd8744c5a3c1951075c03902
  client_secret: 5d4d00d31df44dfa90e0c977aba41534
  username: z7gpo4dn8ekqawcrln0420x26
  redirect_uri: http://SpotifytoTidal:8080


# uncomment this block if you want to only sync specific playlist IDs
#sync_playlists:
sync_playlists:
  - spotify_id: https://open.spotify.com/user/z7gpo4dn8ekqawcrln0420x26?si=34a38688f0a94f56
    tidal_id: https://tidal.com/browse/user/65565825

# uncomment this block if you want to sync all playlists in the account with some exceptions
#excluded_playlists:
#  - spotify:playlist:1ABCDEqsABCD6EaABCDa0a

# default setting for syncing favorites when no command line arguments are provided
#   - when true:  favorites will be synced by default (overriden when any command line arg provided)
#   - when false: favorites can only be synced manually via --sync-favorites argument
sync_favorites_default: true

# increasing these parameters should increase the search speed, while decreasing reduces likelihood of 429 errors
max_concurrency: 10 # max concurrent connections at any given time
rate_limit:      10 # max sustained connections per second
